[[headers]]

for = "/*"

[headers.values]

Content-Security-Policy = "frame-ancestors pig-dice-game.netflify.com"
Referrer-Policy = "strict-origin"
Strict-Transport-Security = "max-age=31536000"
X-Content-Type-Options = "nosniff"
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
proxy_hide_header = "X-Powered-By"

NODE_VERSION = "8"
YARN_VERSION = "1.3.2"